// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmnhdlxjycovmxcegubl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtbmhkbHhqeWNvdm14Y2VndWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NjAxMzYsImV4cCI6MjA1NTAzNjEzNn0.bcuvzg1TBGMgafgqwh8Hd9JHf7Kl7k_Urup-TPpdLiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);